name: Build Image

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build and push image
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Image
        id: build-image
        uses: redhat-actions/buildah-build@v2
        with:
          image: container-vulnerability-scanner
          tags: latest ${{ github.sha }}
          containerfiles: |
            ./Containerfile
